version: 2
updates:
  - package-ecosystem: "nuget"
    directories:
      - "."
      - "/samples/local/Spiffe.Sample.Grpc.Mtls"
      - "/samples/docker/Spiffe.Sample.AspNetCore.Jwt"
      - "/samples/docker/Spiffe.Sample.AspNetCore.Mtls"
      - "/samples/docker/Spiffe.Sample.AspNetCore.Tls"
      - "/samples/docker/Spiffe.Sample.Grpc.Mtls"
      - "/samples/docker/Spiffe.Sample.Grpc.Tls"
    schedule:
      interval: "weekly"
      day: "wednesday"
    open-pull-requests-limit: 5
